name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Adjust this version if needed
          cli_config_credentials_token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform changes
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve
